fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#oc_user:
#    resource: "@OCUserBundle/Controller/"
#    type:     annotation
#    prefix:   /

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login_check:
    path: /login_check

logout:
    path: /logout
