<?php

namespace OC\PlatformBundle\Repository;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $author
     * @return Advert[]
     */
    public function findByAuthorWithoutLazyLoading(string $author) : array{
        $qb = $this->createQueryBuilder('advert');
        
        $qb->where('advert.author = :author')
            ->setParameter('author',$author)
            ->orWhere('advert.author=:seb')
            ->setParameter('seb',"Seb")
        ;
        
        
        return $qb->getQuery()->getResult();
        
        
        
        
    }
}
