<?php

namespace OC\PlatformBundle\Repository;
use OC\PlatformBundle\Entity\Advert;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return Advert
     */
    public function findLastWithComments() : Advert{
        $qb = $this->createQueryBuilder('advert');
        
        $qb->orderBy('advert.id',"DESC")
            ->setMaxResults(1)
            ->leftJoin('advert.comments','comments')
            ->addSelect('comments')
            ;
        
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    
}
